### ISSUE TITLE
support offering

### ISSUE THREAD

**Issue by radu022003** [Dreanaught/JU-Control#41]
Hello, I am also interested in this topic (ju-control) and I can support.
I have tried to sniff the communication and the most relevant info found, because the communication is encrypted, was the ip address of the server myjudo.eu
I tried to sniff the communication over the local network but the index.html is not providing anything useful. 
If you can share some information about the communication protocol would be really helpful.

Best regards

**Comment by Dreanaught** [comment]
Hello @radu022003,
i am sorry, that i haven't read your message back then when you wrote it. Actually i stumbled upon it today.
If you are still interested here are my findings having a judo i-soft SAFE+.
The device itself does not have some sort of web-server where one can log in to and see what's going on. To view my device stats i have to connect it to the judo-portal "myjudo.eu". From there on i am able to view the stats of the device in the portal through a browser or the corresponding android application.
I tried to sniff on the hardware busses of the device but with my limited lab-hardware and knowledge i wasn't able to find out neither the type of bus nor the encoding used.
I ended up requesting the data from the servers as the judo-portal and the app does. The crome dev-tools came in really handy back then.
For the log-in (through the integration) to work one has to log-in to the portal on the browser frist. I don't know why this has to be done but it worked for me :).
With the help of a template sensor i was able to bring the consumtion into the HA Energy-Dashboard.
```# calculate battery energy consumption and delivery
template:
  - sensor:
      - name: "Wasserverbrauch m3"
        unique_id: Wasserverbrauch_m3
        device_class: water
        unit_of_measurement: "m³"
        state_class: total_increasing
        state: "{{ states('sensor.ju_control_gesamtwasserverbrauch') | float * 0.001}}"
```
![image](https://user-images.githubusercontent.com/7461410/221350183-ed2c6253-5f2d-4507-9a42-ca4eb198bbc5.png)
